/**
 * 扩展用户画像 — 10 个额外画像，覆盖 OMA 引擎的边缘场景。
 * 与 user-profiles.ts 中的 5 个基础画像合并使用，总计 15 个。
 */

import type { UserProfile } from "./user-profiles.ts";

export const EXTENDED_PROFILES: UserProfile[] = [
  {
    id: "newbie",
    name: "新手用户",
    description: "刚接触系统，消息简短模糊，经常不知道自己要什么，很少纠正",
    tierDistribution: [0.5, 0.45, 0.05],
    correctionRate: 0.15,
    templates: {
      light: [
        "这是什么",
        "怎么用",
        "嗯？",
        "不太懂",
        "然后呢",
        "这个是干嘛的",
        "哦",
        "好吧",
        "再说一遍",
        "我看看",
      ],
      tracked: [
        "帮我看看这个怎么弄",
        "这个东西怎么装",
        "报错了怎么办",
        "帮我弄一下",
        "我想改个东西但不知道在哪",
        "这个命令怎么用",
        "帮我查下这个问题",
        "我想试试这个功能",
        "教我怎么配置这个",
        "这个文件在哪里",
      ],
      delegation: [
        "帮我把整个项目搭起来",
        "我不太懂，你帮我全部搞定",
      ],
    },
    correctionPhrases: {
      up: ["这个好像需要更多帮助"],
      down: ["太复杂了我看不懂", "简单点"],
    },
  },

  {
    id: "devops",
    name: "运维工程师",
    description: "专注部署/监控/事故响应，高频 tracked，紧急时需要 delegation",
    tierDistribution: [0.1, 0.7, 0.2],
    correctionRate: 0.6,
    templates: {
      light: [
        "ok",
        "收到",
        "已确认",
        "好",
        "看到了",
      ],
      tracked: [
        "帮我检查一下 nginx 的配置有没有问题",
        "查看 Docker 容器的日志",
        "重启一下 Redis 服务",
        "帮我看看磁盘空间还剩多少",
        "检查 SSL 证书到期时间",
        "帮我配置一下防火墙规则",
        "查一下这个端口被谁占了",
        "帮我看看 Kubernetes pod 的状态",
        "同步一下生产环境的配置",
        "帮我排查一下网络延迟问题",
        "更新一下 DNS 记录",
        "帮我看看 CPU 占用异常的原因",
        "备份一下数据库",
        "帮我看看 systemd 服务状态",
        "检查一下 crontab 配置",
        "帮我清理一下过期的日志文件",
        "更新一下服务器的安全补丁",
        "帮我看看负载均衡的分配情况",
      ],
      delegation: [
        "线上出事故了，需要同时排查数据库、网络和应用层",
        "搭建完整的监控体系：Prometheus + Grafana + AlertManager",
        "做一次全面的安全扫描，包括端口、漏洞、配置审计",
        "设计并实现蓝绿部署方案",
        "全面检查生产环境的高可用配置，出报告",
      ],
    },
    correctionPhrases: {
      up: [
        "这个需要多方面同时排查",
        "应该派 agent 并行处理",
      ],
      down: [
        "直接做就行了",
        "不用搞这么复杂",
      ],
    },
  },

  {
    id: "data-scientist",
    name: "数据科学家",
    description: "偏重数据分析和模型训练，消息中夹杂大量英文术语",
    tierDistribution: [0.15, 0.55, 0.3],
    correctionRate: 0.45,
    templates: {
      light: [
        "ok",
        "好的",
        "明白",
        "看到了",
        "thanks",
        "got it",
      ],
      tracked: [
        "帮我看一下这个 DataFrame 的统计信息",
        "跑一下这个 SQL 查询看看结果",
        "帮我画个 distribution plot",
        "检查一下 missing values",
        "帮我做个 feature engineering",
        "跑一下 XGBoost baseline",
        "帮我看看模型的 confusion matrix",
        "优化一下这个 query 的性能",
        "帮我写个 data pipeline",
        "检查一下数据质量",
        "帮我做个 A/B test 的统计分析",
        "把这个 notebook 里的结果整理一下",
        "帮我看看 correlation matrix",
        "跑一下 hyperparameter tuning",
      ],
      delegation: [
        "全面分析这个数据集：EDA + feature selection + 多模型对比 + 报告",
        "搭建完整的 ML pipeline：数据清洗 → 特征工程 → 训练 → 评估 → 部署",
        "并行跑 5 种模型做 benchmark，每个模型出 performance report",
        "做一个端到端的推荐系统 POC",
        "组建团队分别做 data cleaning、modeling 和 deployment",
      ],
    },
    correctionPhrases: {
      up: [
        "这个需要更系统的分析",
        "应该多模型并行对比",
      ],
      down: [
        "不用这么复杂，quick analysis 就行",
        "just run the basic stats",
      ],
    },
  },

  {
    id: "frontend-dev",
    name: "前端开发者",
    description: "专注 UI/UX，React/Vue 相关任务多，很少需要多 agent",
    tierDistribution: [0.2, 0.7, 0.1],
    correctionRate: 0.5,
    templates: {
      light: [
        "好的",
        "ok",
        "收到",
        "可以",
        "嗯",
        "nice",
        "看起来不错",
      ],
      tracked: [
        "帮我修一下这个组件的样式问题",
        "这个页面在手机端布局错乱了",
        "帮我加个 loading 状态",
        "优化一下首屏加载速度",
        "帮我写个 custom hook",
        "修一下这个 React 组件的 re-render 问题",
        "帮我配置 Tailwind CSS",
        "加一个暗色模式切换",
        "帮我做个表单验证",
        "修一下 Safari 上的兼容性问题",
        "帮我写个响应式布局",
        "优化一下图片懒加载",
        "帮我加个动画效果",
        "修一下 Webpack 打包配置",
        "帮我看看 Lighthouse 分数怎么提高",
      ],
      delegation: [
        "重构整个组件库，统一设计系统",
        "全面优化性能：代码分割 + 缓存策略 + CDN + 图片优化",
        "组建团队做一次完整的 accessibility audit",
      ],
    },
    correctionPhrases: {
      up: ["这个需要系统性地解决"],
      down: [
        "这个我自己改改就行",
        "不用派 agent，就是个样式问题",
        "直接改 CSS 就好了",
      ],
    },
  },

  {
    id: "bilingual",
    name: "双语用户",
    description: "频繁中英文切换，技术术语用英文，指令用中文",
    tierDistribution: [0.15, 0.55, 0.3],
    correctionRate: 0.5,
    templates: {
      light: [
        "ok got it",
        "好的 thanks",
        "understood",
        "可以 proceed",
        "嗯 sounds good",
        "roger that",
      ],
      tracked: [
        "help me debug 这个 API endpoint",
        "run the test suite 看看有没有 regression",
        "帮我 review 这个 PR",
        "check if the deployment pipeline is healthy",
        "帮我 set up 一下 CI/CD",
        "我需要 migrate 这个 database schema",
        "can you optimize 这个 query",
        "帮我 implement 一个 retry mechanism",
        "look into this memory leak issue",
        "帮我 write unit tests for this module",
        "configure the staging environment",
        "帮我 analyze 这个 error log",
        "refactor this service to use dependency injection",
      ],
      delegation: [
        "I need a full architecture review，所有 module 都要 cover",
        "set up complete observability: logging + metrics + tracing + alerting",
        "帮我 orchestrate 一个 multi-service migration plan",
        "do a comprehensive security audit, 每个 surface 都要 check",
        "组建 team 分别 handle frontend refactor, backend optimization, and infra upgrade",
      ],
    },
    correctionPhrases: {
      up: [
        "this needs multi-agent coordination",
        "应该 dispatch agents to handle this",
      ],
      down: [
        "just do it directly",
        "不需要 multi-agent，简单处理",
      ],
    },
  },

  {
    id: "rapid-fire",
    name: "连珠炮用户",
    description: "发消息极快极短，一个任务拆成多条消息发，light 消息占比极高",
    tierDistribution: [0.6, 0.35, 0.05],
    correctionRate: 0.3,
    templates: {
      light: [
        "等等",
        "对了",
        "还有",
        "补充一下",
        "忘了说",
        "另外",
        "接上条",
        "改一下",
        "算了",
        "还是不要了",
        "重新来",
        "先这样",
        "继续",
        "下一个",
        "嗯",
        "好",
      ],
      tracked: [
        "帮我看下日志",
        "检查状态",
        "重启服务",
        "查端口",
        "看进程",
        "清缓存",
        "改配置",
        "跑测试",
        "查报错",
        "拉代码",
      ],
      delegation: [
        "全面检查一遍系统",
        "把所有服务都更新一下",
      ],
    },
    correctionPhrases: {
      up: ["这个应该系统做"],
      down: ["简单搞", "直接来"],
    },
  },

  {
    id: "architect",
    name: "架构师",
    description: "关注系统设计和架构决策，消息长且结构化，大量 delegation",
    tierDistribution: [0.05, 0.3, 0.65],
    correctionRate: 0.7,
    templates: {
      light: [
        "好的",
        "同意",
        "方案A",
        "继续",
        "可以",
      ],
      tracked: [
        "帮我画一下这个系统的架构图",
        "评估一下微服务拆分的方案",
        "帮我设计这个模块的 API 接口",
        "分析一下当前系统的瓶颈",
        "帮我做个技术方案对比",
        "review 一下这个数据库的表结构设计",
      ],
      delegation: [
        "设计一个完整的微服务架构方案，包含服务拆分、通信协议、数据一致性、容错策略",
        "全面评估系统可扩展性：\n1. 计算层水平扩展方案\n2. 存储层分片策略\n3. 缓存层架构\n4. 消息队列选型",
        "组建架构评审团队，从安全性、可用性、性能、可维护性四个维度评估方案",
        "设计 event-driven 架构，包含 event store、CQRS、saga 模式的完整方案",
        "做一个完整的技术债务清理计划，按优先级排列所有需要重构的模块",
        "全面设计 API gateway 方案：路由、鉴权、限流、熔断、灰度发布",
        "评估从单体到微服务迁移的完整路径，每个阶段都要有回滚方案",
        "设计分布式事务解决方案，对比 2PC、TCC、Saga 的适用场景",
        "出一份完整的容量规划报告，包含流量模型、资源预估、成本分析",
        "全面审查当前的 observability 方案，提出改进建议",
      ],
    },
    correctionPhrases: {
      up: [
        "这个需要全局视角来分析",
        "应该多维度并行评估",
        "需要组建专项团队",
        "这不是单点问题，需要系统性解决",
      ],
      down: [
        "先聚焦核心问题",
        "不用展开太多",
      ],
    },
  },

  {
    id: "chatty",
    name: "闲聊型用户",
    description: "大量非工作消息，闲聊/问候/吐槽居多，真正工作请求很少",
    tierDistribution: [0.7, 0.25, 0.05],
    correctionRate: 0.2,
    templates: {
      light: [
        "今天天气不错",
        "周末有什么计划",
        "你觉得 AI 会取代程序员吗",
        "好无聊啊",
        "最近好累",
        "午饭吃什么好",
        "哈哈哈",
        "有意思",
        "说得对",
        "你真棒",
        "厉害了",
        "学到了",
        "原来如此",
        "涨知识了",
        "666",
        "你说得有道理",
        "我也这么觉得",
        "确实",
      ],
      tracked: [
        "帮我查个东西",
        "看看这个链接是什么",
        "帮我翻译一下这段话",
        "这个错误是什么意思",
        "帮我写个简单的脚本",
        "看看这个配置对不对",
      ],
      delegation: [
        "帮我做一个完整的项目方案",
        "全面分析一下这个技术选型",
      ],
    },
    correctionPhrases: {
      up: ["这个其实挺复杂的"],
      down: ["不用那么认真", "随便看看就行", "不用太正式"],
    },
  },

  {
    id: "perfectionist",
    name: "完美主义者",
    description: "对结果要求极高，频繁要求重做/修改，纠正率最高",
    tierDistribution: [0.1, 0.5, 0.4],
    correctionRate: 0.9,
    templates: {
      light: [
        "再想想",
        "不够好",
        "重新来",
        "还差点",
        "可以更好",
        "再改改",
      ],
      tracked: [
        "这个代码风格不对，帮我重新写",
        "错误处理不够完善，补全所有 edge case",
        "测试覆盖率不够，补充更多测试用例",
        "性能还能优化，帮我 profiling 一下",
        "文档不够详细，每个函数都要有注释",
        "这个 API 设计不够优雅，重新设计",
        "变量命名不够清晰，帮我重命名",
        "这个模块耦合太紧，帮我解耦",
        "日志输出不够规范，统一格式",
        "这个方案考虑不够全面，补充边界情况",
      ],
      delegation: [
        "全面重构这个模块，代码质量要达到最高标准",
        "从零设计一个完美的 CI/CD 流水线，每个环节都要有质量门禁",
        "做一次极致的性能优化，每个接口的 P99 延迟都要低于 50ms",
        "完美的代码审查：安全、性能、可读性、可测试性、可维护性全覆盖",
        "设计一个零停机部署方案，任何故障都要在 30 秒内自动恢复",
        "组建团队做全面的代码质量提升，lint + format + type safety + test coverage 全上",
      ],
    },
    correctionPhrases: {
      up: [
        "这个需要更深入的处理",
        "应该派 agent 做更全面的分析",
        "用多 agent 保证质量",
        "这不够，需要更系统的方案",
      ],
      down: [
        "这次简单做就行",
      ],
    },
  },

  {
    id: "context-switcher",
    name: "多线程用户",
    description: "同时处理多个项目，消息主题频繁切换，容易让分类器困惑",
    tierDistribution: [0.15, 0.55, 0.3],
    correctionRate: 0.55,
    templates: {
      light: [
        "回到刚才那个",
        "先放一下",
        "切到另一个项目",
        "等等，先处理别的",
        "ok 继续",
        "好，回来了",
      ],
      tracked: [
        "先看看 A 项目的 bug",
        "切到 B 项目，帮我查下部署状态",
        "回到 A 项目，那个 bug 修好了吗",
        "C 项目需要加个新功能",
        "帮我看看 D 项目的测试结果",
        "切到 E 项目，帮我配置环境",
        "回来看 B 项目，刚才的部署怎么样了",
        "A 项目还有个问题要处理",
        "先暂停，帮我处理一下紧急的 hotfix",
        "hotfix 搞完了，回到 C 项目",
        "对了 D 项目的那个数据库问题解决了吗",
        "同时帮我看看 A 和 B 的代码质量",
      ],
      delegation: [
        "三个项目同时推进：A 的重构、B 的部署、C 的新功能",
        "并行处理所有项目的 CI/CD 问题",
        "组建团队分别看 A、B、C 三个项目的技术债",
        "全面检查所有项目的安全漏洞",
        "每个项目都需要出一份进度报告",
      ],
    },
    correctionPhrases: {
      up: [
        "这些项目需要并行推进",
        "应该每个项目派一个 agent",
      ],
      down: [
        "一个一个来就行",
        "不用同时搞",
      ],
    },
  },
];
